trigger:
- main

pool:
  name: Default

steps:
- script: |
    docker build -t demo-app:latest .
  displayName: Docker Image Build

- script: |
    kubectl create -f deployment.yaml --dry-run=client -o yaml
    kubectl create -f service.yaml --dry-run=client -o yaml
  displayName: Kubernetes Manifest Validation


