trigger:
- main

pool:
  name: Default   # Agent'ın olduğu pool

steps:
- script: docker version
  displayName: Docker Version Test

- script: docker build -t agent-test .
  displayName: Docker Build Test

- script: docker run --rm agent-test
  displayName: Docker Run Test